services:
  localstack:
    container_name: localstack-1
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./entrypoint.sh:/etc/localstack/init/ready.d/entrypoint.sh
      - "/var/run/docker.sock:/var/run/docker.sock"

  app:
    build: .
    container_name: app-1
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - FLASK_APP=app
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
